# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
    ]
