# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('WORN', 'Worn'), ('BAD', 'Bad')], default='GOOD', max_length=4)),
                ('Ad_Description', models.TextField(blank=True, default='', verbose_name='Ad Description')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='textbook_app.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('isbn', models.DecimalField(decimal_places=0, max_digits=13, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('description', models.TextField(blank=True, default='', verbose_name='Textbook Description')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook_app.Textbook'),
        ),
        migrations.AddField(
            model_name='ad',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
