# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='isbn',
            field=models.DecimalField(decimal_places=0, max_digits=13, primary_key=True, serialize=False, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Book Title'),
        ),
    ]
