# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0002_auto_20170731_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Ad_Description',
            field=models.TextField(default=' ', verbose_name='Ad Description'),
            preserve_default=False,
        ),
    ]
