# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0002_auto_20170801_0308'),
        ('textbook_app', '0003_ad_ad_description'),
    ]

    operations = [
    ]
