# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0003_ad_ad_description'),
        ('textbook_app', '0002_auto_20170731_2220'),
    ]

    operations = [
    ]
