# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0004_merge_20170801_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='description',
            field=models.TextField(verbose_name='Textbook Description'),
        ),
    ]
