# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0004_merge_20170801_2138'),
        ('textbook_app', '0005_auto_20170801_1017'),
    ]

    operations = [
    ]
