# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0006_merge_20170803_0111'),
        ('textbook_app', '0005_auto_20170801_2146'),
    ]

    operations = [
    ]
