# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0007_merge_20170804_0648'),
        ('textbook_app', '0005_auto_20170802_2351'),
    ]

    operations = [
    ]
